# Generated by Django 3.0 on 2020-01-24 14:13

from django.db import migrations, models
import geolocation_fields.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', geolocation_fields.models.fields.PointField(verbose_name='Point')),
            ],
        ),
    ]
